version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - redmine-network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  mysql-redmine:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      -  MYSQL_ROOT_PASSWORD=
      -  MYSQL_USER=
      -  MYSQL_PASSWORD=
      -  MYSQL_DATABASE=
    networks:
      - redmine-network
  redmine:
    image: redmine:4.1.0
    restart: always
    ports:
      - "3000:3000"
    networks:
      - redmine-network
    environment:
      -  VIRTUAL_HOST=luigi.redmine.com
      -  VIRTUAL_PORT=3000
      -  REDMINE_DB_MYSQL=mysql-redmine
      -  REDMINE_DB_USERNAME=
      -  REDMINE_DB_PASSWORD=
      -  REDMINE_DB_DATABASE=redmine
networks:
  redmine-network:
    driver: bridge
