version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - '8080:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  mysql-redmine:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    networks:
      - redmine-red
    volumes:
      - ./dataMysqlRedmine:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_USER: redmineuser
      MYSQL_PASSWORD: usersecret
      MYSQL_DATABASE: redmine
  
  redmine:
    image: redmine:4.0.4
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./dataRedmine/archivos:/usr/src/redmine/files
      - ./dataRedmine/plugins:/usr/src/redmine/plugins
      - ./dataRedmine/themes:/usr/src/redmine/themes
    environment:
      VIRTUAL_HOST=www.test.redmine.com
      VIRTUAL_PORT=3000
      REDMINE_DB_USERNAME= redmineuser
      REDMINE_DB_PASSWORD= usersecret
      REDMINE_DB_DATABASE= redmine
networks:
  redmine-red:
